# -----------------------------------------------------------------------------
# Social integration
# -----------------------------------------------------------------------------
# If you want to list your social media, add the link to the list below.
# The icons are FontAwesome icons.

email: linfeng0419@gmail.com
google_scholar: https://scholar.google.com/citations?user=PyRqpAsAAAAJ&hl=zh-CN
github: https://github.com/Linfeng-Tang
research_gate: https://www.researchgate.net/profile/Tang-Linfeng-2
zhihu: https://www.zhihu.com/people/timer-69
# 注意：al-folio 默认可能没有 CSDN 图标，填入后如果没有显示，是因为模板缺少该图标的定义
csdn: https://blog.csdn.net/fovever_

# 【新增】ORCID (已帮你填好)
orcid: https://orcid.org/0000-0002-8566-5743

# 【新增】微信二维码 (请确保你已上传图片 assets/img/wechat_qr.png)
wechat_qr: assets/img/wechat_qr.png

# 下面这些保持注释或删除
# linkedin: https://www.linkedin.com/in/your-linkedin-profile
# twitter: https://twitter.com/your-twitter-handle